server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://192.168.1.128:3306/cirssdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: wangqiubao
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.criss.wang.entity